### ISSUE TITLE
JS C@E build error "too much recursion"

### ISSUE THREAD

**Issue by Integralist** [fastly/js-compute-runtime#1]
A customer raised an issue in the CLI repo here:
https://github.com/fastly/cli/issues/361

I'll be investigating why the CLI didn't stop the 'build' process once Wiser had reported an error, but I believe the rest of the comments in that issue are best discussed here.

**Comment by tschneidereit** [comment]
I'm investigating the JS runtime issue now, and probably know what we need to do to fix it.

**Comment by JakeChampion** [comment]
This looks to be solved, I've tried reproducing with all the examples that @JakeChampion has given but they all now compile and work on C@E - I've tried reassigning to the same variable over 200,000 times in the top-level and still can not hit the error
