### ISSUE TITLE
Response and Request classes are missing the clone() method

### ISSUE THREAD

**Issue by roptch** [fastly/js-compute-runtime#10]
Both classes are based on the WHATWG specs as written at the top of their reference pages ([Request](https://js-compute-reference-docs.edgecompute.app/classes/request.html) - [Response](https://js-compute-reference-docs.edgecompute.app/classes/response.html)) but they are lacking the `clone()` method.
Would it be possible to add it or is it done on purpose ?
Thanks ! :)

**Comment by tschneidereit** [comment]
Thank you for filing this—that would indeed be possible, yes. There are
some more urgent things to work through right now (including breaking
changes to get out of the way, such as #8), but we should be able to get to
this before too long.

**Comment by bjrn** [comment]
Hi, any updates on this?

**Comment by tschneidereit** [comment]
@bjrn yes, we do have a meaningful update to share: while Request/Response clone didn't make the cut for the new release, we now have the foundations in place to properly implement them. #64 contains significant changes to how Request/Response bodies are handled, after which clone is fairly straightforward to implement (and before which it was close to impossible to do so in a spec-compliant way.)

We'll have another release out in a few weeks containing `clone` and a few other nice additions.

**Comment by bjrn** [comment]
That's really good news, thanks for getting back!

**Comment by jamesarosen** [comment]
As of 5debe806a4a40e0d3b07bdd6b71489aa7d739cff, `Request#clone` should be working properly.
