### ISSUE TITLE
Improve handling of hostcall errors

### ISSUE THREAD

**Issue by tschneidereit** [fastly/js-compute-runtime#11]
In a lot of places, we currently turn a hostcall error code into a JS exception containing the error code and the C++ source location of the hostcall. That's very rarely helpful in debugging JS code, and we should improve on it :)

**Comment by JakeChampion** [comment]
@tschneidereit I just came across the mapping of hostcall error codes within the [fastly-shared crate](https://docs.rs/fastly-shared/0.6.3/src/fastly_shared/lib.rs.html#35-96) and thought I'd have a go at contributing to this project -- I've started a [draft pull-request](https://github.com/fastly/js-compute-runtime/pull/24) with the error messages from the crate
