### ISSUE TITLE
Missing globals `URL` and `URLSearchParams`

### ISSUE THREAD

**Issue by JakeChampion** [fastly/js-compute-runtime#2]
Hi, this is likely the wrong place to open this issue but I could not find a public repository for the `@fastly/js-compute` npm package

I wanted to report that `URL` and `URLSearchParams` are [documented on the website](https://js-compute-reference-docs.edgecompute.app/classes/url.html) to exist but they don't actually exist when running the code using `fastly compute serve` or deploying it to Fastly

I can see that the [compute-starter-kit-javascript-default](https://github.com/fastly/compute-starter-kit-javascript-default) uses Webpack and a polyfill from Core-JS to provide these globals - would it be possible to provide these polyfills within the `@fastly/js-compute` package itself?

https://github.com/fastly/compute-starter-kit-javascript-default/blob/22fe9f050d8a2c715d23da5ea29935765192566d/webpack.config.js#L15-L19

**Comment by tschneidereit** [comment]
No, this is the perfect place to report this, thank you! 😄 

I think providing the polyfills in `js-compute` would indeed be the better solution than doing it in the starter kit, yes. However, I actually just completed a native implementation of both `URL` and `URLSearchParams` today, and should be able to publish a new version of the SDK with those included soon. Some testing and then reviews of some somewhat hairy code still pending, though.

**Comment by JakeChampion** [comment]
WooHoo! 🎉 

If you want a customer to test it out, let me know and I'll update my service to start using it :-)

**Comment by tschneidereit** [comment]
@JakeChampion while #4 is still awaiting review and internal testing against our SDK test suite, I think it's ready for early testing :) You can do that by downloading a build from the GitHub Action run [here](https://github.com/fastly/js-compute-runtime/actions/runs/1094174258). Should work by extracting the zip and moving the contained binary into the correct folder under `node_modules/@fastly/js-compute/bin`.
