### ISSUE TITLE
JS_GC trap issue.

### ISSUE THREAD

**Issue by wilsonwang371** [fastly/js-compute-runtime#201]
Hi,

I am using this repo and execute the runtime on wasmtime. 

What I observed is that 1 out of 3 times if I call JS_GC at the end of the function that I called, js-compute-runtime can trigger a HeapOutOfBound trap in wasmtime.

Is there any suggestions on this why this is happening?

Thanks

**Comment by alekhanetweb** [comment]
@wilsonwang371 sorry to comment on an old issue ...but how does one execute the runtime on wasmtime ? im looking to try and do the same
