### ISSUE TITLE
Allow setting cache key for outgoing requests

### ISSUE THREAD

**Issue by williamoverton** [fastly/js-compute-runtime#260]
Provide an equivalent of [set_cache_key_str](https://docs.rs/fastly/latest/fastly/experimental/trait.RequestCacheKey.html#tymethod.set_cache_key_str) from the rust sdk.

Example usecase:

I wish to cache a request based in the city a user is in. e.g. 
```
fetch("https://api.com", {
    cacheKey: `${event.request.url}/${event.request.geo.city}`
})
```

**Comment by AndrewBarba** [comment]
This is already possible with a `CacheOverride`:

```typescript
const cacheOverride = new CacheOverride('override', {
  ttl: 365 * 24 * 3600,
  swr: 365 * 24 * 3600,
  surrogateKey: 'some_cache_key'
})

fetch("https://api.com", {
  cacheOverride: originCache
})
```

**Comment by JakeChampion** [comment]
This is implemented in https://github.com/fastly/js-compute-runtime/pull/281 and will be out in the next release 👍
