### ISSUE TITLE
fastly.allowDynamicBackends in version 0.5.4

### ISSUE THREAD

**Issue by metadaddy** [fastly/js-compute-runtime#289]
The current version of `@fastly/js-compute-runtime` at npm is 0.5.4, published 9/28/22. The [changelog](https://unpkg.com/@fastly/js-compute@0.5.4/CHANGELOG.md) mentions that it's now possible to enable dynamic backends with

```javascript
fastly.allowDynamicBackends = true;
```

Running my app with `fastly compute serve` results in an error:

```text
% fastly compute serve
✓ Initializing...
✓ Verifying package manifest...
✓ Verifying local javascript toolchain...
✓ Running [scripts.build]...
✓ Creating package archive...

SUCCESS: Built package (pkg/package.tar.gz)

✓ Running local server...

Oct 14 13:51:46.726 ERROR unknown import: `fastly_http_req::register_dynamic_backend` has not been defined
Error: Other(unknown import: `fastly_http_req::register_dynamic_backend` has not been defined)

ERROR: error during execution process:

Oct 14 13:51:46.726 ERROR unknown import: `fastly_http_req::register_dynamic_backend` has not been defined
Error: Other(unknown import: `fastly_http_req::register_dynamic_backend` has not been defined).

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

I can publish my app to Compute@Edge ok, but at runtime, when I make a request, it fails with

```text
stderr | d177a668 | Error while running request handler: register_dynamic_backend: Unsupported operation error. This error is thrown when some operation cannot be performed, because it is not supported. - Fastly error code 5
stderr | d177a668 | 
stderr | d177a668 | Stack:
stderr | d177a668 |   o@<stdin>:2:219
stderr | d177a668 |   @<stdin>:2:866
stderr | d177a668 |   @<stdin>:2:1381
stderr | d177a668 | 
```

Coming here, I don't see 0.5.4 in the tags, so I'm confused. Did 0.5.4 get released? Was it released, then unreleased? If so, then it needs to be deleted from npm.

**Comment by JakeChampion** [comment]
Hi @metadaddy, thanks for the report. After publishing to npm we noticed the change-log missed an important step about dynamic backends and we updated the change-log in this repository to include the missing step.

>Note: This feature is disabled by default for Fastly Services. Please contact [Fastly Support](https://support.fastly.com/hc/en-us/requests/new?ticket_form_id=360000269711) to request the feature be enabled on the Fastly Services which require Dynamic Backends.
>- https://github.com/fastly/js-compute-runtime/blob/main/sdk/js-compute/CHANGELOG.md#054-2022-09-28


Regarding the git tags in this repository, we don't yet tag from this repository, which is why you can't see a related tag, the release has happened and 0.5.4 is staying on npm.

Right now to use Dynamic Backends, you will need to contact Fastly Support and request the feature be enabled as it is a currently beta feature

**Comment by metadaddy** [comment]
Thanks for clearing things up, @JakeChampion!
