### ISSUE TITLE
Internal error code and line shown when calling Dictionary.get method

### ISSUE THREAD

**Issue by JakeChampion** [fastly/js-compute-runtime#3]
I have an edge dictionary named `aliases` containing an item named `default`, when I try to get the item the service throws an error internal to the runtime, which I've posted below:
The error: `/home/runner/work/fst-js-compute-runtime/fst-js-compute-runtime/c-dependencies/js-compute-runtime/../js-compute-runtime/js-compute-builtins.cpp:1789 (get) - Fastly error code 3`

That error comes from this function: https://github.com/fastly/js-compute-runtime/blob/0043e1be06aecbea03ab7808d474d445b37bb484/c-dependencies/js-compute-runtime/js-compute-builtins.cpp#L1779-L1792

I'm not sure what is causing the code to error unfortunately -- hopefully this is enough information to help figure out the root cause

**Comment by JakeChampion** [comment]
This happens when wizer tries to pre-initiatilise `new Dictionary("...")` -- when that happens, wizer will end up the in path which creates and return a DictionaryHandle with an invalid handle set
-- https://github.com/fastly/js-compute-runtime/blob/59602c6ea397918c158fe5fc0d30e84b363120b8/c-dependencies/js-compute-runtime/js-compute-builtins.cpp#L1846

I looked into wizer but couldn't find documentation on how to mark functions as not pre-initialisable.

I worked around the issue by putting changing my javascript code to no longer have Dictionary construction within the realms of wizer's optimising/pre-initialising.

E.G.
```js
new Dictionary('aliases');
```
will fail due to getting pre-initialised with an invalid dictionary-handle
placing the construction into a function stops wizer from gettign to it
```js
function getAliasDict() {
	return new Dictionary('aliases');
}
```

**Comment by tschneidereit** [comment]
@JakeChampion thank you for reporting and investigating this!

I think there are two things wrong here:
1. We don't support creating `Dictionary` objects at init time.
2. We don't detect that that's what's happening, and instead pretend that all's fine.

We could easily fix the second one by throwing an error if the `Dictionary` ctor is called at init time. However, I think it's very useful to be able to do this, so fixing the first one instead seems better. We can detect that we're running at init time and defer the associated hostcall in the ctor to happen at runtime instead.

One thing I'll note is that I'm not sure how high a priority this should be, relative to other issues we're working on, so this might not make the next release.

**Comment by JakeChampion** [comment]
That sounds ideal, thanks @tschneidereit
