### ISSUE TITLE
Missing `FormData` and `Request.formData`

### ISSUE THREAD

**Issue by JakeChampion** [fastly/js-compute-runtime#34]
I'm building a C@E app which reads a html form submission but I found that `FormData` and the helper method `Request.formData` currently are not implemented in the runtime.

Are these planned to be implemented in the runtime?

**Comment by tschneidereit** [comment]
Yes, we do plan to support them! I unfortunately can't right now give a good estimate of when they'll be available, though, as we haven't yet finalized planning for future feature work for JS.

**Comment by JakeChampion** [comment]
> Yes, we do plan to support them! I unfortunately can't right now give a good estimate of when they'll be available, though, as we haven't yet finalized planning for future feature work for JS.

That's okay, it's good to hear they will be supported. I've included a polyfill for `FormData` which works, I'm looking forward to when I can delete all the polyfills 😄

**Comment by br0p0p** [comment]
any update on this? 

My team is in the process of migrating two sizable Remix apps to C@E and removing our reliance on `FormData` would be a substantial effort.

I've tried several different strategies to polyfill `FormData` without success.

The polyfill @JakeChampion mentioned above was bespoke for a private project. As a last ditch effort if there are no other paths forward, we could potentially do the same but would really prefer a less involved solution.

**Comment by guybedford** [comment]
Moving to https://github.com/bytecodealliance/StarlingMonkey/issues/116.
