### ISSUE TITLE
`{locked: false}` body in HEAD requests

### ISSUE THREAD

**Issue by ilyasmez** [fastly/js-compute-runtime#352]
The `HEAD` request seem to now have a body, with the value `{locked: false}`, and this shouldn't be the case, as HEAD requests should not have a body.
This issue causes this error:
```
Error while running request handler: Request constructor: HEAD or GET Request cannot have a body.
```
when trying to re-use a request, like in the case of rewrites: https://developer.fastly.com/learning/compute/migrate/#modify-a-request-url-path

ℹ️ This issue is reproducible in `v0.7.0` and `v1.0.0`, everything seems to work fine in `v0.6.0` and below.

An example of a problematic HEAD request:
<img width="861" alt="after-upgrade" src="https://user-images.githubusercontent.com/30146019/208086244-22c1b3e3-0c6b-49a0-932b-7d68ded203cb.png">

the same request but with `@fastly/js-compute@v0.6.0`:
<img width="792" alt="before-upgrade" src="https://user-images.githubusercontent.com/30146019/208086247-0b622c65-73fa-4293-91a5-17ecfa2d1352.png">

You can see that the `body` property in the first screenshot has a value of `{locked: false}` while it should be `null`.

**Comment by JakeChampion** [comment]
Thank you for reporting this @ilyasmez - I've been able to replicate the issue and know where the bug was introduced, I'm working on resolving this now 👍

**Comment by ilyasmez** [comment]
Awesome! Thank you @JakeChampion.
