### ISSUE TITLE
Error building wasm with JS compiled from TS

### ISSUE THREAD

**Issue by twhid** [fastly/js-compute-runtime#368]
I really want to use TS and expressly while writing code for compute@edge. But, when I generate JS from a file and then pass that to `js-compute-runtime` I get a `wizer` error. This same file seems to work fine when passed directly (ie no webpack). 

Note: that I believe it has something to do with a dep in expressly. I have gotten it to work using more vanilla sample code.

Once webpack has transpiled `index.ts` to `./bin/index.js`, then..
```
$ npx js-compute-runtime ./bin/index.js ./bin/main.wasm
Exception while evaluating JS: (new TypeError("undefined is not a non-null object", "<stdin>", 1063))
  @<stdin>:1063:14
  @<stdin>:1064:5
  @<stdin>:1065:3

Error: the `wizer.initialize` function trapped

Caused by:
    Exited with i32 exit status 1
    wasm backtrace:
        0: 0x410c19 - <unknown>!<wasm function 6531>
        1: 0x410c21 - <unknown>!<wasm function 6532>
        2: 0x413233 - <unknown>!<wasm function 6542>
        3: 0x2bec9 - <unknown>!<wasm function 242>
        4: 0x3f550 - <unknown>!<wasm function 245>
        5: 0x3f725 - <unknown>!<wasm function 247>
```

When I run `faslty compute serve` with this in the build script...

```
npm exec js-compute-runtime src/index.js
```
...then the JS compiles and works. 

For reference and (hopefully) debugging, the source files are in this gist:
https://gist.github.com/twhid/7a94d808283678cebeb493b6911dd678

The gist includes the webpack compiled JS (which wizer chokes on) and the source files.

**Comment by JakeChampion** [comment]
Hi @twhid, thanks for the question

I've gone ahead and made [an example application using TypeScript and Expressly](https://github.com/JakeChampion/compute-starter-kit-typescript-expressly).

Let me know if that helps or if you have some more questions 🤞

**Comment by twhid** [comment]
Hi @JakeChampion ! Thanks so much!  I set it up locally and tested and works great.

What was I missing? I assume it was something in the webpack config. Perhaps the resolve.fallback? Or the ProviderPlugin?

Thanks again

**Comment by JakeChampion** [comment]
I am not sure what was missed, the provided gist didn't contain a webpack or typescript configurations unfortunately. 
I'm glad to hear the example works for you, we will likely turn it into an official fastly starter-kit to make it more visible for others to benefit from 😊

**Comment by twhid** [comment]
Oops. Yes, of course. I should have provided those.

I think a TypeScript starter will be very popular :) Many people are unfamiliar with this new runtime of Fastly's. Configuring one's project can be a challenge! 

Thanks again!
