### ISSUE TITLE
Missing precompiled binary for Wizer on linux arm64

### ISSUE THREAD

**Issue by mattiasottosson** [fastly/js-compute-runtime#411]
Hi!  

I'm running @fastly/js-compute inside Docker on Apple Silicon, and unfortunately ran into some problems due to the missing precompiled binary.

```
ERROR: error during execution process:

file:///app/node_modules/@jakechampion/wizer/index.js:17
  throw new Error(`Unsupported platform: "${platformKey}". "@jakechampion/wizer does not have a precompiled binary for the platform/architecture you are using. You can open an issue on https://github.com/bytecodealliance/wizer/issues to request for your platform/architecture to be included."`);
        ^

Error: Unsupported platform: "linux arm64 LE". "@jakechampion/wizer does not have a precompiled binary for the platform/architecture you are using. You can open an issue on https://github.com/bytecodealliance/wizer/issues to request for your platform/architecture to be included."
    at pkgForCurrentPlatform (file:///app/node_modules/@jakechampion/wizer/index.js:17:9)
    at file:///app/node_modules/@jakechampion/wizer/index.js:20:13
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async file:///app/node_modules/@fastly/js-compute/js-compute-runtime-cli.js:20:38

Node.js v18.0.0.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

I thought I could get around it by manually installing Wizer through cargo, but it dosen't seem to be a way to manually specify the path to the binary, since it's imported from "@jakechampion/wizer" here:
https://github.com/fastly/js-compute-runtime/blob/main/src/compileApplicationToWasm.js#L6

which in turn requires it from the pre defined set here:
https://github.com/bytecodealliance/wizer/blob/main/npm/wizer/index.js#L4-L9

I requested a precompiled binary for linux arm64, but is there something you can do meanwhile to manually define the path to Wizer?

**Comment by njfamirm** [comment]
i have this issue too

```
build:app
0.689 > js-compute-runtime app/index.js
0.689 
/app/node_modules/@bytecodealliance/wizer-linux-x64/wizer: not found
2.771 Error: Failed to compile JavaScript to Wasm:  Wizer initialization failure
```

**Comment by JakeChampion** [comment]
@njfamirm which version of the @fastly/js-compute-runtime are you using?

**Comment by njfamirm** [comment]
> @njfamirm which version of the @fastly/js-compute-runtime are you using?

The project I'm building don't uses this, but uses @fastly/js-compute version 2.3.0

I am trying to build the [polyfill](https://github.com/Financial-Times/polyfill-service) project

I create an [issue](https://github.com/Financial-Times/polyfill-service/issues/2752) in this project and with an update this issue was closed but I still have this issue

**Comment by njfamirm** [comment]
this is my latest [Dockerfile](https://github.com/AliMD/alwatr/blob/12a682dca708ef84299ca125eb4a2ccdceff0589/cloud/container/polyfill/Dockerfile)

**Comment by njfamirm** [comment]
this log of my container build

```
RUN ls -lrth node_modules/@bytecodealliance/wizer/

total 40K    
-rwxr-xr-x    1 root     root         853 Jun 25 15:47 wizer.js
-rw-r--r--    1 root     root        5.5K Jun 25 15:47 update.js
-rw-r--r--    1 root     root        1.1K Jun 25 15:47 package.json
-rw-r--r--    1 root     root         968 Jun 25 15:47 package-helpers.js
-rw-r--r--    1 root     root         727 Jun 25 15:47 index.js
-rw-r--r--    1 root     root         332 Jun 25 15:47 README.md
-rw-r--r--    1 root     root       12.0K Jun 25 15:47 LICENSE.md
```

**Comment by njfamirm** [comment]
https://github.com/fastly/js-compute-runtime/blob/a030a0328e756f99f327d045655501ea08fcabd9/src/compileApplicationToWasm.js#L6

js extension might solve the problem?

**Comment by JakeChampion** [comment]
@njfamirm can you try using yarn instead of npm in this line please? 
https://github.com/AliMD/alwatr/blob/12a682dca708ef84299ca125eb4a2ccdceff0589/cloud/container/polyfill/Dockerfile#L19
 npm has a bug when installing optionaldependencies which have os and CPU filter fields

**Comment by njfamirm** [comment]
still have error

https://github.com/AliMD/alwatr/actions/runs/5371299545/jobs/9743965079

**Comment by JakeChampion** [comment]
@njfamirm I have confirmed that wizer is installed correctly in your dockerfile, your issue different, your issue looks to stem from the fact that the dockerfile you have written is using alpine with musl libc and the fact that the linker for wizer is `/lib/ld-musl-aarch64.so.1`, which your alpine+musl environment does not have that installed:
```
5ddffbbed157:/app# ls -la "node_modules/@bytecodealliance/wizer-linux-arm64/wizer"
total 19656
drwxr-xr-x    2 root     root          4096 Jun 25 23:20 .
drwxr-xr-x    6 root     root          4096 Jun 25 23:20 ..
-rw-r--r--    1 root     root           206 Jun 25 23:19 index.js
-rw-r--r--    1 root     root           399 Jun 25 23:19 package.json
-rwxr-xr-x    1 root     root      20110872 Jun 25 23:19 wizer

5ddffbbed157:/app/node_modules/@bytecodealliance/wizer-linux-arm64# patchelf --print-interpreter wizer
/lib/ld-linux-aarch64.so.1

5ddffbbed157:/app/node_modules/@bytecodealliance/wizer-linux-arm64# ls -la /lib/ld-linux-aarch64.so.1
ls: /lib/ld-linux-aarch64.so.1: No such file or directory

5ddffbbed157:/app/node_modules/@bytecodealliance/wizer-linux-arm64# ls -la /lib/ld-musl-aarch64.so.1
-rwxr-xr-x    1 root     root        657784 May  2 03:49 /lib/ld-musl-aarch64.so.1
```

if you want pre-built wizer binaries using musl, you will need to raise an issue on the [wizer project](https://github.com/bytecodealliance/wizer)

**Comment by njfamirm** [comment]
Your efforts to help me are admirable!
Thank you @JakeChampion
