### ISSUE TITLE
[FEATURE REQUEST] Support --env like fastly compute serve

### ISSUE THREAD

**Issue by domdomegg** [fastly/js-compute-runtime#418]
`fastly compute serve` supports an `--env` option as described [here](https://developer.fastly.com/reference/compute/fastly-toml/#environments) which tells the CLI to look for `fastly.toml` with a suffix, e.g. `--env local` would use `fastly.local.toml`.

This is a useful feature for managing different environments. Could the equivalent, or something similar, be built into js-compute-runtime?

**Comment by JakeChampion** [comment]
Thanks for the issue @domdomegg. The js-compute-runtime does not use fastly.toml - could you expand some more on the feature request and the problem it is solving?

**Comment by domdomegg** [comment]
Ignore this issue 🤦

I think I managed to confuse myself as to what CLI was complaining about a missing `fastly.toml`. My bad!
