### ISSUE TITLE
JWS signing runs very slowly

### ISSUE THREAD

**Issue by domdomegg** [fastly/js-compute-runtime#436]
Reproduction: https://github.com/domdomegg/fastly-jws-signing

(can't use fiddle as it doesn't support external deps)

Fastly takes about ~10,000ms to sign a JWT using the jsrsasign library (a JS-native implementation of crypto functions), on a production-enabled service. When running with `fastly compute serve` it takes ~2,000ms on my machine.

In the browser this takes ~3ms. My understanding is that this is doing the same amount of work: it doesn't defer to a built in crypto module here. So I think fastly should be able to reach similar performance.

I'd also be happy with alternative suggestions on how to generate a JWT on Fastly (e.g. other libraries - however these are limited by the execution environment not having crypto built-ins), or otherwise authenticate against Google APIs with OAuth2 on Fastly :)

**Comment by domdomegg** [comment]
It seems to be a performance issue with binary operations (e.g. via JWS.sign -> RSAKey.doPublic -> jsbn.bnModPow -> jsbn.squareTo -> jsbn.am). An even smaller example:

```js
const doMaths = () => {
  let xl = 1;
  for (let i = 0; i < 10_000_000; i++) {
    xl++ & 0x1234;
  }
}

addEventListener("fetch", event => {
  // NB: date is not the most reliable way of getting time, but process.hrtime is not defined in the fastly environment
  const t1 = new Date().getTime()
  doMaths()
  const t2 = new Date().getTime()
  const message = `Doing maths took ${t2 - t1}ms`
  console.log(message)

  event.respondWith(new Response(message));
});
```

In the browser, this runs in ~8ms. In `fastly compute serve` it takes ~6000ms, and on Fastly itself takes ~30,000ms.

**Comment by JakeChampion** [comment]
Closing this as we now have it implemented natively 👍
