### ISSUE TITLE
Can js-compute-runtime be run completely locally?

### ISSUE THREAD

**Issue by guest271314** [fastly/js-compute-runtime#445]
Can js-compute-runtime be run completely locally? 

Or  does the application work only by making remote requests to Fastly?

**Comment by JakeChampion** [comment]
You an run it completely locally yes, the [fastly cli](https://developer.fastly.com/learning/tools/cli/) offers that functionality via `fastly compute serve` (https://developer.fastly.com/reference/cli/compute/serve/) or you can use [viceroy](https://github.com/fastly/viceroy)

**Comment by guest271314** [comment]
> The CLI interacts with Fastly via our [API](https://developer.fastly.com/reference/api/), authenticated using an API token.

> This will start a local server (by default at: http://127.0.0.1:7878), which can be used to make requests to your Compute@Edge service locally.

I need clarification. 

I **do not** want to make **any remote requests** just to use js-compute-runtime.


By local I mean locally, without having anything to do with some online service.

It would be helpful to put together a complete tutorial for how to achieve that.

**Comment by guest271314** [comment]
Another important question before I even get started is 

1. Are any configuration files _necessary_?
2. Do you restrict by design pattern one request body being streamed to a different request? workerd does that, and says they won't change that behaviour (the user has no control over the code they are running on their own machine at that point) https://github.com/cloudflare/workerd/issues/423#issuecomment-1457410315
> This restriction is fundamental to workerd operation and won't be changing
3. Are serving and uploading streams (Streams Standard) supported?

**Comment by guest271314** [comment]
> You can run it completely locally yes, the [fastly cli](https://developer.fastly.com/learning/tools/cli/) offers that functionality via `fastly compute serve`

I fetched the `fastly` executable. I don't see any option to run the following completely locally; this is no option to run a file that I can see

```
async function app(event) {
    const request = event.request;
    return new Response(`You made a request to ${request.url}`)
}

addEventListener("fetch", event => {
  event.respondWith(app(event));
});
```

> (https://developer.fastly.com/reference/cli/compute/serve/) or you can use [viceroy](https://github.com/fastly/viceroy)

> To install Viceroy as a standalone tool, you'll need to first [install Rust](https://www.rust-lang.org/tools/install) if you haven't already.

That dependency is non-trivial on a temporary file system running on RAM. Rust tool chain is over 1GB to install.

I downloaded to `viceroy` executable. The expected parameter is

```
viceroy bin/main.wasm
```
How are you compiling the above JavaScript to WASM?

**Comment by JakeChampion** [comment]
> > The CLI interacts with Fastly via our [API](https://developer.fastly.com/reference/api/), authenticated using an API token.
> 
> > This will start a local server (by default at: http://127.0.0.1:7878), which can be used to make requests to your Compute@Edge service locally.
> 
> I need clarification.
> 
> I **do not** want to make **any remote requests** just to use js-compute-runtime.
> 
> By local I mean locally, without having anything to do with some online service.
> 
> It would be helpful to put together a complete tutorial for how to achieve that.

`fastly compute serve` does not require a Fastly token and does not interact with Fastly infrastructure. The other commands available in the cli are what require the token for use when interacting with Fastly infrastructure. 

If you run `fastly compute init` and follow the interactive prompts to install a JavaScript application, you can then run `npm install ` and `fastly compute serve` to run it locally

**Comment by JakeChampion** [comment]
> > You can run it completely locally yes, the [fastly cli](https://developer.fastly.com/learning/tools/cli/) offers that functionality via `fastly compute serve`
> 
> I fetched the `fastly` executable. I don't see any option to run the following completely locally; this is no option to run a file that I can see
> 
> ```
> async function app(event) {
>     const request = event.request;
>     return new Response(`You made a request to ${request.url}`)
> }
> 
> addEventListener("fetch", event => {
>   event.respondWith(app(event));
> });
> ```
> 
> > (https://developer.fastly.com/reference/cli/compute/serve/) or you can use [viceroy](https://github.com/fastly/viceroy)
> 
> > To install Viceroy as a standalone tool, you'll need to first [install Rust](https://www.rust-lang.org/tools/install) if you haven't already.
> 
> That dependency is non-trivial on a temporary file system running on RAM. Rust tool chain is over 1GB to install.
> 
> I downloaded to `viceroy` executable. The expected parameter is
> 
> ```
> viceroy bin/main.wasm
> ```
> 
> How are you compiling the above JavaScript to WASM?

To compile the JS application, you need to download the npm package of this repository, which is published under the name `@fastly/js-compute`, you can then use the cli in that npm package to compile the code, and then use viceroy to run it locally. You will need a fastly toml file to configure backends and stores for local development https://developer.fastly.com/reference/compute/fastly-toml/

**Comment by guest271314** [comment]
> To compile the JS application, you need to download the npm package of this repository

So installing Node.js is a requirement?

I normally don't install `node` executable locally or globally. I just fetch the nightly release and get rid of everything except the `node` executable and run that from the current (download) directory.

Configuring `npm` from the Node.js nightly release to work without installing the Node.js archive globally requires tediously modifying multiple files - because Node.js expects to be installed and provides no default option to run `npm` without Node.js being installed.

> You will need a fastly toml file to configure backends and stores for local development https://developer.fastly.com/reference/compute/fastly-toml/

It would be helpful to create a complete example of doing what you describe - without relying on Node.js being installed to fetch the npm package - unless js-compute-runtime really is dependent on Node.js.

**Comment by JakeChampion** [comment]
The js-compute-runtime requires npm and node for it's CLI to compile an application to WASM, the runtime itself does not require npm or node.

The examples are on the [Fastly Developer Portal](https://developer.fastly.com/learning/compute/javascript/), which is where we also document the fastly.toml configuration file and [how to run completely locally](https://developer.fastly.com/learning/compute/testing#running-a-local-testing-server).
