### ISSUE TITLE
Serialisation issue with Headers and Set-Cookie

### ISSUE THREAD

**Issue by williamoverton** [fastly/js-compute-runtime#47]
When setting set-cookie headers with `header.append()` there can sometimes be an issue where the set-cookie header is serialised into one header which is comma seperated:
![image](https://user-images.githubusercontent.com/2838108/139453411-263c0418-21cc-42f7-b20d-cdf3f0d7cb56.png)

This is not accepted as multiple cookies by browsers, after some digging I have found that this only happens when using a Header object which is then passed as a HeaderInit object when creating a response.

This works (creates multiple headers):
```javascript
addEventListener("fetch", (event) => {
  let r = new Response("Hello");

  r.headers.append("Set-Cookie", "test=1");
  r.headers.append("Set-Cookie", "test2=2");
  r.headers.append("Set-Cookie", "test3=3");
  
  event.respondWith(r)
});
```

This does not (single comma separated header):
```javascript
addEventListener("fetch", (event) => {
  let h = new Headers();

  h.append("Set-Cookie", "test=1");
  h.append("Set-Cookie", "test2=2");
  h.append("Set-Cookie", "test3=3");
  
  event.respondWith(new Response("Hello", {
    headers: h
  }))
});
```

**Comment by AndersDJohnson** [comment]
@JakeChampion @williamoverton Any updates on this one? It's a really critical feature before we can use Fastly Compute@Edge with JavaScript.

We need to be able to `fetch` to a backend, and get multiple `Set-Cookie` headers from its response.
And then also reconstruct a new `Response` with those multiple `Set-Cookie` headers plus some additional ones.

**Comment by AndersDJohnson** [comment]
I can confirm @williamoverton's observation that `response.headers.append(...)` seems to work in that it adds additional headers of the same name without overwriting existing ones.

But beyond that, we're still blocked. For example, when trying to re-create a new response by cloning one but modifying its body, e.g.:

```js
const newResponse = new Response('new body', {
  headers: originalResponse.headers
});
```

The multiple headers of the same name are collapsed into a single one with comma-separated value.

**Comment by AndersDJohnson** [comment]
For what's it's worth, it does seem to work to pull `Set-Cookie` header from the original response, split it with `set-cookie-parser`'s `splitCookiesString`, then clone it with `new Response('new body', originalResponse)` and call `newResponse.headers.delete('Set-Cookie')` then loop thru the split cookies and call `newResponse.headers.append(...)` for each, and then proceed with any custom logic to append more `Set-Cookie` headers at will.
