### ISSUE TITLE
`?` appended to URLs if `searchParams` methods are accessed

### ISSUE THREAD

**Issue by twhid** [fastly/js-compute-runtime#484]
Greetings,

I've noticed that if `searchParams`  methods are accessed on an instance of a [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) then a question mark is always appended to the url.

To reproduce: 

Use this handler in an empty JS starter kit:
```js
/// <reference types="@fastly/js-compute" />

addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));

async function handleRequest(event) {
    const urlObj = new URL('http://www.example.com');
    console.log('href 1 = ', urlObj.href);
    urlObj.searchParams.sort();
    console.log('href 2 = ', urlObj.href);
    return new Response("OK", { status: 200 });
}

```

Then, run `fastly compute serve` and request `http://127.0.0.1:7676` 

Console output:
```shell
INFO: Listening on http://127.0.0.1:7676

INFO: Command output:
--------------------------------------------------------------------------------
Log: href 1 =  http://www.example.com/
Log: href 2 =  http://www.example.com/?
```

I'll admit to having not read the spec 😉 but, this behavior doesn't appear to be to spec. Other JS runtime examples:

A file like this in node v18.15.0:
```js
const http = require('http');
const port = 8080;
const server = http.createServer((req, res) => {
    const reqUrl = new URL('http://www.example.com:8080');
    console.log('href 1 = ', reqUrl.href);
    reqUrl.searchParams.sort();
    console.log('href 2 = ', reqUrl.href);
    res.end('OK');
});
server.listen(port);
console.log(`Node server listening on ${port}`);
```

Outputs:
```
Node server listening on 8080
href 1 =  http://www.example.com:8080/
href 2 =  http://www.example.com:8080/
```

And the Firefox and Chrome consoles output: 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/299945/230948905-cfb6a801-2adf-4491-924d-5c14233cbf6c.png">

+++

Working around this apparent bug creates more complexity than is required for certain scenarios.

Thank you for any feedback.

**Comment by JakeChampion** [comment]
Thank yo for providing a small amount of code which shows the issue 🙏 This Fiddle uses the code you have provided and confirms this is happening https://fiddle.fastly.dev/fiddle/5cffcaa3 -- I can also confirm that this is a bug in our URL implementation 👍 

The bug is in this function:
https://github.com/fastly/js-compute-runtime/blob/main/c-dependencies/js-compute-runtime/rust-url/src/lib.rs#L35-L49

It shouldn't be too difficult to fix this, you really helped speed up the process with your code example and mentioning it happens on more than one URLSearchParams method, thank you!

**Comment by twhid** [comment]
Great thx @JakeChampion

> The bug is in this function:
https://github.com/fastly/js-compute-runtime/blob/main/c-dependencies/js-compute-runtime/rust-url/src/lib.rs#L35-L49

I did track it down to that being the mostly likely place but my rust isn't good enough so I couldn't provide a suggested fix.
