### ISSUE TITLE
How to know it's running on Fastly or not

### ISSUE THREAD

**Issue by yusukebe** [fastly/js-compute-runtime#517]
Hi, thank you for the great runtime and JavaScript environment. This is just a question.

Our framework [Hono](https://github.com/honojs/hono) runs on multi-runtimes like Cloudflare Workers, Deno, Bun, Fastly Compute@Edge, and so on. It can detect which runtime the application is running on.

```ts
const runtimeName = c.runtime() // such as `workerd`, `bun`, or `deno`.
```

For example, in the Deno case, it enables us to detect whether it is on Deno or others with the following code:

```ts
if (global?.Deno !== undefined) {
  return 'deno'
}
```

Then, I want to know how it can know if it runs on Fastly Compute@Edge or not. I know there is `fastly:*`, so we can use it with "dynamic require":

```ts
const { env } = require('fastly:env')
if (env instanceof Function) onFastly = true
```

But, sometimes, with this method, the error occurs when using a `webpack`:

https://github.com/honojs/hono/issues/1052

It's good that we can get such as `global.fastly`. Is there a good way?

**Comment by JakeChampion** [comment]
Thanks!
`globalThis.fastly` exists already, you could use that as a way to decide whether Hono is running on fastly JS

**Comment by yusukebe** [comment]
Hi @JakeChampion !

Great! We'll use it!

**By the way**, we are using [jest-preset-fastly-js-compute](https://github.com/ysugimoto/jest-preset-fastly-js-compute) by @ysugimoto -san for testing with Jest. It seems not to have `globalThis.fastly`.

@ysugimoto:
Do you have any plan to add `globalThis.fastly`?

**Comment by ysugimoto** [comment]
@yusukebe @JakeChampion 

Sure, I will support `globalThis.fastly` on https://github.com/ysugimoto/jest-preset-fastly-js-compute/pull/7 👍

**Comment by yusukebe** [comment]
@ysugimoto  -san

Great! Thank you!
