### ISSUE TITLE
Build failed with SpiderMonkey release library

### ISSUE THREAD

**Issue by fuxiaohei** [fastly/js-compute-runtime#520]
Follow this doc https://github.com/fastly/js-compute-runtime/blob/main/DEVELOPMENT.md. It show errors below:

![image](https://user-images.githubusercontent.com/2142787/237030994-5338cefb-ea5f-41a4-b0fc-556de9925c57.png)

I find it compiles SpiderMonkey in CI workflow, not use release library. 

I use `(cd runtime/spidermonkey && sh build-engine.sh release)` to get SpiderMoneky in local. Everything is ok.

Is the `SpiderMonkey release library` broken ?

**Comment by JakeChampion** [comment]
Thanks for the report @fuxiaohei -- I have opened a pull-request to fix this now 🙇 https://github.com/fastly/js-compute-runtime/pull/521
