### ISSUE TITLE
js-compute-runtime builds are not indempotent

### ISSUE THREAD

**Issue by mlegenhausen** [fastly/js-compute-runtime#531]
Steps to reproduce

```
fastly compute init
// Initialize a JavaScript project with "Empty starter for JavaScript"
npm i

npx js-compute-runtime ./src/index.js ./bin/main.wasm && sha512sum ./bin/main.wasm
// c150a5cdaf8507e78d7ab2e08d5b227bb759ba49db9560e6a2b5ef38d5a4fb29086f72fdb6b3a54d981eceea7ffb2a0791602eacf19564fa5d29c87c1a066aea  bin/main.wasm

npx js-compute-runtime ./src/index.js ./bin/main.wasm && sha512sum ./bin/main.wasm
// c59a7369e67949c148dfd11522825659d52745bc0908e787f6b00ef8e7efd4b06e7c8a864ee05ed4d670bb6bab302468f8e1c51055518f951e46d7e1e381b17f bin/main.wasm
```

The `sha512sum` checksum changes on every execution of `js-compute-runtime` even when the source `./src/index.js` file is not changed. This makes it a lot harder to deploy applications e. g. with the terraform fastly provider which requires a checksum to detect a change.

See other problems with unstable checksums in the fastly CLI: https://github.com/fastly/cli/issues/743

For everybody looking for a workaround you can use the following `build` script instead:

```
sha512sum -c ./bin/checksum.txt > /dev/null || (js-compute-runtime ./src/index.js ./bin/main.wasm && sha512sum ./src/index.js > ./bin/checksum.txt)
```

**Comment by andrebenedetti** [comment]
Looks like this is also being tracked in the issue [Hash of compute packages changes without changes to the contents #743](https://github.com/fastly/cli/issues/743) in fastly-cli

**Comment by guybedford** [comment]
I believe this has been resolved, but please reopen if it is still an issue.
