### ISSUE TITLE
Provide useful implementations of `toString()` and `toJSON()` for important builtin objects

### ISSUE THREAD

**Issue by tschneidereit** [fastly/js-compute-runtime#55]
Logging important builtin objects such as `Request`, `Response`, `FetchEvent`, etc currently doesn't result in useful output. To address this, we should evaluate for which we can implement `toString()` and `toJSON()` in useful ways.

Note that we might not be able to do useful things for all of them, because the stringification behavior is fixed by specifications for some or all of them. E.g. `JSON.stringify(new Request("http:example.com"))` results in the string `"{}"` in browsers.

**Comment by JakeChampion** [comment]
We went with the console approach in the end 👍 https://github.com/fastly/js-compute-runtime/pull/204
