### ISSUE TITLE
No access to tls.client

### ISSUE THREAD

**Issue by jamesarosen** [fastly/js-compute-runtime#560]
I'm trying to port some VCL to C@E, but the original has things like

```tpl
tls.client.servername # https://developer.fastly.com/reference/vcl/variables/client-connection/tls-client-servername/
tls.client.ja3_md5 # https://developer.fastly.com/reference/vcl/variables/client-connection/tls-client-ja3-md5/
```

Given the existing API, I might expect something like

```ts
import { client } from "fastly:tls";

client.servername
client.ja3_md5
```

Or perhaps chained off `FetchEvent.prototype` like `client.{address,geo}`:

```ts
fetchEvent.tls.servername
```

**Comment by JakeChampion** [comment]
Thanks for this issue @jamesarosen - I have a draft PR #562 which should hopefully resolve this for you 🤞
