### ISSUE TITLE
feature-request: support for SubtleCrypto encrypt and decrypt for AES-CBC and AES-GCM

### ISSUE THREAD

**Issue by JakeChampion** [fastly/js-compute-runtime#578]
* `SubtleCrypto.prototype.encrypt`
* `SubtleCrypto.prototype.decrypt`

Both with support for `AES-CBC` and `AES-GCM`

_Originally posted by @mlegenhausen in https://github.com/fastly/js-compute-runtime/issues/440#issuecomment-1550974081_

**Comment by guybedford** [comment]
Moved to https://github.com/bytecodealliance/StarlingMonkey/issues/124.
