### ISSUE TITLE
Feature request: SubtleCrypto support for RSA-PSS, ECDSA, ED25519, pkcs8 and spki

### ISSUE THREAD

**Issue by JakeChampion** [fastly/js-compute-runtime#579]
If I could lobby for a few more algorithms to be supported 🙏 

- `RSA-PSS`
- `ECDSA` (at least P-256, but ideally all three curves)
- `Ed25519` from https://wicg.github.io/webcrypto-secure-curves/
- almost forgot, the goto JWS algorithm - `HMAC`

Also `pkcs8` and `spki` key format import/export are not to be overlooked. Developers LOOOVE to use in favour of JWKs.

I have a comprehensive [test suite](https://github.com/panva/jose#supported-runtimes) for different runtimes' webcrypto implementations that I could unload on js-compute-runtime eventually.

_Originally posted by @panva in https://github.com/fastly/js-compute-runtime/issues/440#issuecomment-1535339296_

**Comment by jfctfl** [comment]
Would this also include `RS256`? 🙂 We need `RS256` to be able to verify JWTs from Fanout in a c@e js runtime - for more context: https://developer.fastly.com/learning/concepts/real-time-messaging/fanout/#validating-grip-requests

**Comment by JakeChampion** [comment]
@jfctfl We support RS256, but that is not what Fanout uses, Fanout uses EC P-256, which we do not support and is already listed in this issue 👍

**Comment by guybedford** [comment]
Moved to https://github.com/bytecodealliance/StarlingMonkey/issues/123.
