### ISSUE TITLE
setTimeout support?

### ISSUE THREAD

**Issue by krvajal** [fastly/js-compute-runtime#63]
`setTimeout` does not seem to work

**Comment by bberman3** [comment]
Have you tried https://docs.fastly.com/en/guides/changing-connection-timeouts-to-your-origin ?

**Comment by krvajal** [comment]
That does not look like setTimeout to me.

**Comment by JakeChampion** [comment]
Pull-request for JS Timers is https://github.com/fastly/js-compute-runtime/pull/293
Hopefully that will be in either the next release or the one after that 🤞
