### ISSUE TITLE
package.json exports order change breaks fastly compute build

### ISSUE THREAD

**Issue by andersjanmyr** [fastly/js-compute-runtime#662]
I don't know if this is a bug in the `js-compute-runtime` resolver or if it's some other problem, but
the following change (ordering of keys inside exports) breaks `fastly compute build`.

```
✘ [ERROR] Could not resolve "node:path"

    node_modules/eta/dist/eta.module.mjs:1:22:
      1 │ import * as path from 'node:path';
        ╵                       ~~~~~~~~~~~
```

```patch
  "exports": {
    "types": "./dist/types/index.d.ts",
+    "import": "./dist/eta.module.mjs",
    "browser": "./dist/browser.umd.js",
    "require": "./dist/eta.umd.js",
-    "import": "./dist/eta.module.mjs",
    "default": "./dist/eta.umd.js"
  },
```
https://github.com/eta-dev/eta/commit/acea87ce855fb3fa629dc7859f4cea49fdbd3ec6

**Comment by JakeChampion** [comment]
I think that is a bug for eta, that project can target the Fastly Compute platform specifically by adding a `"fastly"` key like so:

```patch
  "exports": {
    "types": "./dist/types/index.d.ts",
    "fastly": "./dist/browser.umd.js",
    "import": "./dist/eta.module.mjs",
    "browser": "./dist/browser.umd.js",
    "require": "./dist/eta.umd.js",
    "default": "./dist/eta.umd.js"
  },
```

**Comment by andersjanmyr** [comment]
A cool. I didn't know about it. Any docs I can link to?

**Comment by andersjanmyr** [comment]
@JakeChampion It only works if I add the `fastly` key before the `import` key.

This fails with the same error.
```
  "exports": {
    "types": "./dist/types/index.d.ts",
    "import": "./dist/eta.module.mjs",
    "fastly": "./dist/browser.umd.js",
```

This works.
```
  "exports": {
    "types": "./dist/types/index.d.ts",
    "fastly": "./dist/browser.umd.js",
    "import": "./dist/eta.module.mjs",
```

Putting it before the import is probably going to fail the `bun` build that was the cause of the initial patch.
https://github.com/eta-dev/eta/pull/250

**Comment by JakeChampion** [comment]
I believe the Package Exports Fields are meant to be order-dependant, `bun` would/should not be using the `"fastly"` export, `bun` would skip that and go to the next field it supports which will be `"import"` 👍
