### ISSUE TITLE
Honojs with Fastly

### ISSUE THREAD

**Issue by rahul007-bit** [fastly/js-compute-runtime#709]
Hi,

I was trying the Honojs with Fastly and doing some experiments with different libraries that I used in my projects.
I found this `@hanazuki/node-jsonnet` is not working and I am getting the following errors,
```
✘ [ERROR] Could not resolve "path"

    bin/index.js:1:573:
      1 │ ...=he((Ss,pt)=>{var ne=require("path").sep||"/";pt.exports=Jt;func...
        ╵                                 ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "fs"

    bin/index.js:1:1023:
      1 │ ...wt=he((j,vt)=>{var Se=require("fs"),oe=require("path"),Xt=mt(),i...
        ╵                                  ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "util"

    bin/index.js:3:767:
      3 │ ...),{Jsonnet:Rt}=Pe,tr=require("util").types.isAsyncFunction,rr=Rt...
```

Does anyone have any idea how to solve it??

**Comment by JakeChampion** [comment]
Howdy,
It looks to me like `@hanazuki/node-jsonnet` depends on running in a nodejs environment and expects nodejs built-in packages to exist such as fs and path. js-compute-runtime is not based on nodejs and does not have the same built-in packages as nodejs, which is why `@hanazuki/node-jsonnet` does not work

**Comment by rahul007-bit** [comment]
Thank you for your reply and time!

the error also suggests that we can specify this `"platform: 'node'"` somewhere,
does this suggest is given by `fastly-compute-runtime` or `honojs`?

and once again Thank you so much for your time!! 🙏🏼

**Comment by JakeChampion** [comment]
Unfortunately setting `"platform: 'node'"` will not solve the issue as that is telling the bundler that your target environment is `node` and so has the node built-ins such as FS and path, but your target environment is not `node` and does not have those built-ins

**Comment by rahul007-bit** [comment]
@JakeChampion That's unfortunate, but is there any way I can read files in the `src` directory like `JSON` or `yaml` files so that I can find some alternative to `@hanazuki/node-jsonnet`

**Comment by JakeChampion** [comment]
Yes, you can include the file during build/compile time using `includeBytes` and then convert to a string and then parse using JSON/yaml.

Something like this:
```js
/// <reference types="@fastly/js-compute" />

import { includeBytes } from "fastly:experimental";

const decoder = new TextDecoder();
const config = JSON.parse(decoder.decode(includeBytes('src/config.json')));

async function app() {
    return new Response("hello");
}
addEventListener("fetch", event => event.respondWith(app(event)));
```

An alternative would be to store the JSON/yaml files in a KV Store and then use the JSON method when reading them:

```js
/// <reference types="@fastly/js-compute" />

import { KVStore } from "fastly:kv-store";

async function app(event) {
  const files = new KVStore('files')

  const entry = await files.get('config')
  const config = await entry.json()
  return new Response("hello")
}

addEventListener("fetch", (event) => event.respondWith(app(event)))

```

**Comment by rahul007-bit** [comment]
This looks perfect!!
Once again, thank you for your time!
