### ISSUE TITLE
":" character in filenames will make the Typescript starter-kit fail under Windows.

### ISSUE THREAD

**Issue by noopole** [fastly/js-compute-runtime#713]
I cannot run the [Typescript starter kit](https://github.com/fastly/compute-starter-kit-typescript/)  on Windows because this **js-compute** module is using the _colon_ `:` character in filenames for [_types_ files](https://github.com/fastly/js-compute-runtime/tree/main/types). For, it's not an authorized character.

It works under Linux though.

See discussion https://github.com/fastly/compute-starter-kit-typescript/pull/4#issuecomment-1817674554

NB: For Javascript starter kits there is a [webpack workaround](https://github.com/fastly/compute-starter-kit-javascript-default/blob/4152856cd2df6e8e10181939f0bba07239d1d0b5/webpack.config.js#L28C2-L36C6), but I'm not sure it's a good solution... anyway I didn't manage to implement it with Typescript!

**Comment by guybedford** [comment]
This was resolved in https://github.com/fastly/js-compute-runtime/pull/726.
