### ISSUE TITLE
Requested backend named '' does not exist

### ISSUE THREAD

**Issue by nico2che** [fastly/js-compute-runtime#716]
Exception since 3.8.0 when no backend specified in `fetch` options, with dynamic backend

Maybe from 9c750e5697bb02676762225e4fdc7589d23e13d9 ?

**Comment by JakeChampion** [comment]
Thanks for the issue, @nico2che and/or @alex8bitw would you be able to provide some code which shows this happening? Unfortunately I am not able to replicate this and the tests we have all look to be passing as well
