### ISSUE TITLE
Support top-level await

### ISSUE THREAD

**Issue by guybedford** [fastly/js-compute-runtime#729]
To support top-level await, it should be enough simply to configure esbuild to transpile it into an immediately executing promise function, where the error handler throws a global error and the completion handler is a noop.

With that, top-level await would correspond to running at preinitialization time since we already drive the event loop for preinitialization.

Later on, we could have more native level support if we support ES modules, but the semantics would remain the same, even on top of an esbuild virtualization.

**Comment by guybedford** [comment]
The blocker here is esbuild not supporting TLA at all for bundling unfortunately.

**Comment by guybedford** [comment]
Actually it turns out that per `Initial support for bundling with top-level await` in https://github.com/evanw/esbuild/releases/tag/v0.10.0 this is supported only for the `esm` output format in esbuild.

We currently use the `iife` output, so switching to the `esm` output sounds like the correct way to achieve this.

**Comment by harmony7** [comment]
This has been implemented and can be enabled an experimental flag `--experimental-enable-top-level-await`, and is available starting v3.11.0.

Should we leave this issue open until it leaves experimental status?
