### ISSUE TITLE
Exception while processing network requests

### ISSUE THREAD

**Issue by aivong3** [fastly/js-compute-runtime#743]
Seeing the following exceptions in logs:

```
Exception while processing network requests: (new Error("process_pending_async_tasks: Invalid handle. Thrown when a request, response, dictionary, or body handle is not valid.\n", ""))
```

They seem to occur after a promise timeout in a handler. We're using the library https://www.npmjs.com/package/promise-timeout and have added try/catch handling for errors.

We still see the exceptions. We also get 500s returned by our edge compute service to a VCL service in a chain. The edge compute service itself does not log any 500s.

**Comment by kpfleming** [comment]
I'm going to close this issue as this channel is not suitable for customer support issues; since your issue has also been reported to the Fastly support team, it will be handled there.
