### ISSUE TITLE
fastly:device

### ISSUE THREAD

**Issue by twhid** [fastly/js-compute-runtime#749]
Greetings,

@fastly/js-compute@npm:3.12.0

Does `Device` work locally? 

I'm getting null for common user-agents. 

Eg: 
```js
import { Device } from 'fastly:device';
Device.lookup('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.3');
// returns nulll
```

Thanks for any clarification!

**Comment by JakeChampion** [comment]
You would need to define the data within fastly.toml's local_server section, here is a link to an example we use in our tests

https://github.com/fastly/js-compute-runtime/blob/d93760eea6cc60bf6b5b5f1409edf3357a62b300/integration-tests%2Fjs-compute%2Ffixtures%2Fapp%2Ffastly.toml.in#L104-L116

**Comment by twhid** [comment]
Thanks @JakeChampion !
