### ISSUE TITLE
bug: Setting cacheKey on Request constructor or during fetch does not work

### ISSUE THREAD

**Issue by harmony7** [fastly/js-compute-runtime#768]
In #281, Request.prototype.setCacheKey() was implemented, which sets the cache key for an outgoing request.

```javascript
const req = new Request("https://example.com/path/to/resource");
req.setCacheKey("foo");
const res = await fetch(req, { backend: "example" });
```

The above example works as expected.
(Header `Fastly-Xqd-Cache-Key: 2C26B46B68FFC68FF99B453C1D30413413422D706483BFA0F98A5E886266E7AE` is present.)

However, setting the cache key directly on the Request or during the fetch call does not work:
```javascript
const req = new Request("https://example.com/path/to/resource", { cacheKey: "foo" }); // Adding cacheKey here
const res = await fetch(req, { backend: "example" });
```

```javascript
const req = new Request("https://example.com/path/to/resource");
const res = await fetch(req, { backend: "example", cacheKey: "foo" }); // Adding cacheKey here
```

(No header `Fastly-Xqd-Cache-Key` is present)

**Comment by harmony7** [comment]
I compared this to `cacheOverride`, which does work.

`setCacheOverride` works by setting the Slot `CacheOverride` on the request object:

```c++
bool Request::set_cache_override(JSContext *cx, JS::HandleObject self,
                                 JS::HandleValue cache_override_val) {
  /* ... */
  JS::SetReservedSlot(self, static_cast<uint32_t>(Slots::CacheOverride),
                      JS::ObjectValue(*override));
  return true;
}
```

and then by applying it during a fetch
```c++
bool fetch(JSContext *cx, unsigned argc, Value *vp) {
  CallArgs args = CallArgsFromVp(argc, vp);
  /* ... */
  if (!builtins::Request::apply_cache_override(cx, request)) {
    return false;
  }
  /* ... */
}
```

This means that cache_override can come from either the Request constructor or the fetch parameter, or be set by the setCacheKey, and they would all be applied the same.

Whereas `setCacheKey` goes ahead and applies the `cacheKey` value directly:
```javascript
bool Request::set_cache_key(JSContext *cx, JS::HandleObject self, JS::HandleValue cache_key_val) {
  /* ... */
  JSObject *headers = RequestOrResponse::headers<builtins::Headers::Mode::ProxyToRequest>(cx, self);
  /* ... */
  JS::RootedObject headers_val(cx, headers);
  JS::RootedValue name_val(cx, JS::StringValue(JS_NewStringCopyN(cx, "fastly-xqd-cache-key", 20)));
  JS::RootedValue value_val(
      cx, JS::StringValue(JS_NewStringCopyN(cx, hex_str.c_str(), hex_str.length())));
  if (!builtins::Headers::append_header_value(cx, headers_val, name_val, value_val,
                                              "Request.prototype.setCacheKey")) {
    return false;
  }
  /* ... */
}
```

The `cacheKey` isn't looked at when the fetch actually occurs.

I believe the behavior of cache key should probably follow the same pattern as cache override - in other words, set_cache_key should set the value of the slot, and then be referenced and applied during fetch.

(Incidentally the current implementation likely also causes a problem during Request cloning, as the new cloned request won't have the cache key applied.)

**Comment by guybedford** [comment]
Thanks for spotting this, it seems we document its support but it wasn't actually implemented. I've added a PR in https://github.com/fastly/js-compute-runtime/pull/770.
