### ISSUE TITLE
Exceptions occurring inside SimpleCache's getOrSet cannot be caught from the outside

### ISSUE THREAD

**Issue by JohanLi** [fastly/js-compute-runtime#777]
Hello!

Stumbled upon a gotcha recently, where this does not behave as expected:

```
try {
  await SimpleCache.getOrSet('key', async () => {
    throw Error()

    return {
      value: 'value',
      ttl: 60
    }
  });
} catch (e) {
  // the exception inside the set callback will not be caught here
}
```

I understand that there's a lot going on under the hood with SimpleCache (request collapsing and all), but it'd be more convenient if you could catch exceptions from the "outside". At the very least, this behavior should be documented.

**Comment by guybedford** [comment]
I agree it would make sense to treat failures on the setter promise as failures of the operation. Thanks for bringing this up.
