### ISSUE TITLE
Support mTLS for dynamic backends

### ISSUE THREAD

**Issue by kphillips** [fastly/js-compute-runtime#794]
Given that the Fastly Rust SDK supports mutual TLS for dynamic backends via [BackendBuilder::provide_client_certificate()](https://docs.rs/fastly/latest/fastly/backend/struct.BackendBuilder.html#method.provide_client_certificate), the Fastly Compute platform is able to support mTLS backend connections.

Please extend this functionality to the JavaScript Compute SDK.

**Comment by guybedford** [comment]
Yes, we can add support for this in the JavaScript compute runtime, it shouldn't be too tricky.

In terms of the API, it can be as simple as adding a new `clientCert` field to the [BackendConfiguration type](https://github.com/fastly/js-compute-runtime/blob/main/types/backend.d.ts#L2), of the form:

```ts
interface ClientCert {
  cert: String,
  key: SecretStoreEntry
}
```

Then we would also need to implement `SecretStore.fromBytes` of the form:

```ts
class SecretStore {
  static fromBytes (bytes: Uint8Array) -> SecretStoreEntry;
}
```

I will aim to implement and land this by early next week, to go out with the next release already adding features to dynamic backends as well.

**Comment by guybedford** [comment]
Support landed in https://github.com/fastly/js-compute-runtime/commit/7d2b7b781ed808d9bcf1fe9584aa31f788b980a2, I'll get a release cycle going now.
