### ISSUE TITLE
allowDynamicBackends(); has no affect on Dynamic Backends.

### ISSUE THREAD

**Issue by alex8bitw** [fastly/js-compute-runtime#800]
Using v3.15.0 of js-compute on Fastly, with Dynamic Backend support enabled:

- Setting allowDynamicBackends(false); at a global scope, does nothing.  Dynamic backends still work fine.
- Setting allowDynamicBackends(true); at a global scope, and allowDynamicBackends(false); at local scope, also does nothing.  Dynamic backends still work fine.
- Setting allowDynamicBackends(false); in both global and local scope, does nothing. Dynamic backends still work fine.
Completely omitting calling allowDynamicBackends(); does nothing. Dynamic backends still work fine.

It seems allowDynamicBackends(false); or allowDynamicBackends(true); do nothing.

**Comment by guybedford** [comment]
With `allowDynamicBackends(false)` all calls to `fetch` must have a `backend` property provided. If you are finding this is not the case, can you share a code example of how you are able to achieve this?

**Comment by alex8bitw** [comment]
Here's a Fiddle:  https://fiddle.fastly.dev/fiddle/a1152147
Note that the Fiddle works as it's supposed to.  No backend is setup when allowDynamicBackends(false);  But I find that when I actually upload the Compute code, this value is ignored.

Let me know if you're able to replicate.

**Comment by guybedford** [comment]
@alex8bitw when you say "ignored" do you mean that the application you've provided in the fiddle works correctly on compute instead of failing?

**Comment by alex8bitw** [comment]
I went over the code, and I believe I see the issue.
I was setting allowDynamicBackends(false) in a global scope, but I was also setting the following in a local scope:

  allowDynamicBackends({
    connectTimeout: global_connectTimeout,
    firstByteTimeout: global_firstByteTimeout,
    betweenBytesTimeout: global_betweenBytesTimeout,
  });

The dynamic timeout config overrides the allowDynamicBackends(false), this seems to be by design.

**Comment by guybedford** [comment]
That is correct, the default behaviour is for dynamic backends to be disabled. When calling `allowDynamicBackends` with a value other than `false`, they are enabled.
