### ISSUE TITLE
allowDynamicBackend Global Timeout Values don't work

### ISSUE THREAD

**Issue by alex8bitw** [fastly/js-compute-runtime#812]
Hi,
   Release 3.15.0 of js-compute included global timeout value support.  They don't seem to work.

Here's a Fastly Fiddle as an example: https://fiddle.fastly.dev/fiddle/e4f016a5

**Comment by guybedford** [comment]
Hi @alex8bitw. Fastly Fiddle does not support timeouts, only the compute service does.

**Comment by alex8bitw** [comment]
Is there a way to validate the values are working without setting up custom timeout code at the origin?

**Comment by alex8bitw** [comment]
Another question @guybedford , do the global timeout values, also affect things like connections to Fastly Key Vault store?  I noticed that during timeout events, everything times out, KV connections along with fetch requests.

**Comment by guybedford** [comment]
The timout should just be associated with fetches to the backends for which they apply on compute. Other services may have their own specific timeouts of course too, I'm not sure about the design of those platform-level timeouts though.

**Comment by guybedford** [comment]
The only way to test timeouts is by running a real request on compute with a timeout.

**Comment by alex8bitw** [comment]
Thanks for your help @guybedford I just realized I can use https://http-me.glitch.me/test?wait=20000 outside of a Fiddle, so I can try to test that as a dynamic backend.
