### ISSUE TITLE
Implement two hostcalls for obtaining address/port used to connect to origin

### ISSUE THREAD

**Issue by kpfleming** [fastly/js-compute-runtime#814]
These [two hostcalls](https://github.com/fastly/ExecuteD/blob/30ce2686a4020ea896d6adc4bfc077485adf2a14/wasm_abi/compute-at-edge-abi/compute-at-edge.witx#L643) were recently added. Support for them has already been added in the Rust SDK, but should also be added in the JavaScript SDK.

**Comment by guybedford** [comment]
Thanks for sharing, I will aim to get this together for a release either next week or the week of the 8th of July.

**Comment by guybedford** [comment]
I have some work-in-progress code here, but a release is currently blocked on Viceroy support for these new hostcalls.

**Comment by guybedford** [comment]
This was released in 3.18.0.
