### ISSUE TITLE
Allow commands/arrgs in spawnSync() to contain whitespace

### ISSUE THREAD

**Issue by alharirihamzah** [fastly/js-compute-runtime#820]
Commands and arrgs in `spawnSync()` with paths that includes spaces in them are broken, for example:
`/Users/hamzah/dev/MY APP/src/filename...`

The input in [containsSyntaxErrors](https://github.com/fastly/js-compute-runtime/blob/main/src/containsSyntaxErrors.js#L9) might contain a whitespace "like in my case"
![Screenshot 2024-07-05 at 10 28 17](https://github.com/fastly/js-compute-runtime/assets/42102276/c2678e3d-0f52-44a7-94a0-b15f2de6e92d)

_Note that a similar fix has been done but for the command in [containsSyntaxErrors - L#6](https://github.com/fastly/js-compute-runtime/blob/main/src/containsSyntaxErrors.js#L6)_

The exact same issue occurs while compiling the app to wasm in the command in [compileApplicationToWasm - L#120](https://github.com/fastly/js-compute-runtime/blob/main/src/compileApplicationToWasm.js#L120) and in the arrgs in [compileApplicationToWasm - #L128-#L129](https://github.com/fastly/js-compute-runtime/blob/main/src/compileApplicationToWasm.js#L128-L129)

PR: #821

**Comment by JakeChampion** [comment]
This was fixed by https://github.com/fastly/js-compute-runtime/pull/821 and release in version [v3.16.1](https://github.com/fastly/js-compute-runtime/releases/tag/v3.16.1)
