### ISSUE TITLE
Support auto-decompression for upstream response body streams

### ISSUE THREAD

**Issue by tschneidereit** [fastly/js-compute-runtime#83]
C@E supports automatic decompression for response gzip compressed bodies for upstream responses. The Rust SDK exposes this via a [method on the `Request` struct](https://docs.rs/fastly/latest/fastly/http/struct.Request.html#method.set_auto_decompress_gzip). For the JS runtime, it probably makes sense to expose this as an `autoDecompress: 'gzip`` property on the `Request` constructor's `init` parameter.

**Comment by JakeChampion** [comment]
This should be simpler to support once the DecompressionStream pull-request is merged -> https://github.com/fastly/js-compute-runtime/pull/160

**Comment by guybedford** [comment]
Could we use a special header for this? Even if we don't send such a header and instead use it as a request modification, it avoids going down non-spec API paths and using the existing extension space for HTTP.

**Comment by JakeChampion** [comment]
> Could we use a special header for this? Even if we don't send such a header and instead use it as a request modification, it avoids going down non-spec API paths and using the existing extension space for HTTP.

Great idea! We should likely do the same for setting the cache key and deprecate our Request.prototype.setCacheKey method

**Comment by JakeChampion** [comment]
This was added in [3.2.0](https://github.com/fastly/js-compute-runtime/blob/main/CHANGELOG.md#320-2023-08-10)
