### ISSUE TITLE
AbortController Support

### ISSUE THREAD

**Issue by Abiti-936** [fastly/js-compute-runtime#85]
I am trying to create a Rest API with [Worktop](https://github.com/lukeed/worktop/tree/next) & Faunadb. The Worktop Routing Works, but [Faunadb JS Library](https://github.com/fauna/faunadb-js) needs AbortController which doesn't seems to be Present in the Global Object of Compute@Edge JS Runtime, it says AbortController is not present in global object, you have to Polyfill it. What do you Recommend to do? Is these a Compute@Edge JS Runtime issue?

**Comment by Abiti-936** [comment]
I have found a Library to Polyfill AbortController, but it's necessary to included by default in Compute@Edge JS Runtime. Just see the Library in [here](https://github.com/mysticatea/abort-controller).

**Comment by guybedford** [comment]
Moving to https://github.com/bytecodealliance/StarlingMonkey/issues/118.
