### ISSUE TITLE
Support KVStore v2 hostcalls

### ISSUE THREAD

**Issue by guybedford** [fastly/js-compute-runtime#922]

**Comment by guybedford** [comment]
This is dependent on https://github.com/fastly/Viceroy/pull/427.

**Comment by akanksha-fastly** [comment]
@computermouth recently added new functions and support for more arguments to the existing hostcalls for the KV-store Rust SDK, we would like to support them in JS SDK as well. 
[Here's the link](https://docs.rs/fastly/latest/fastly/kv_store/index.html) for your reference.
